# 基础镜像
FROM redis
# author
MAINTAINER mcx(https://zhaohaoyue.love)

# 挂载目录
VOLUME /home/mcx/cxblog/redis
# 创建目录
RUN mkdir -p /home/mcx/cxblog/redis
# 指定路径
WORKDIR /home/mcx/cxblog/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/mcx/cxblog/redis/redis.conf
