# 基础镜像
FROM nginx
# author
MAINTAINER cxblog

# 挂载目录
VOLUME /home/mcx/cxblog/projects/cxblog-ui
# 创建目录
RUN mkdir -p /home/mcx/cxblog/projects/cxblog-ui
# 指定路径
WORKDIR /home/mcx/cxblog/projects/cxblog-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/mcx/cxblog/projects/cxblog-ui
