# 基础镜像
FROM nginx
# author
MAINTAINER mcx(https://zhaohaoyue.love)

# 挂载目录
VOLUME /home/mcx/cxblog
# 创建目录
RUN mkdir -p /home/mcx/cxblog
# 指定路径
WORKDIR /home/mcx/cxblog
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/admin /home/mcx/cxblog/admin
COPY ./html/web /home/mcx/cxblog/web
COPY ./html/h5 /home/mcx/cxblog/h5
COPY ./html/doc /home/mcx/cxblog/doc
