# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER mcx(https://zhaohaoyue.love)

# 挂载目录
VOLUME /home/mcx/cxblog
# 创建目录
RUN mkdir -p /home/mcx/cxblog
# 指定路径
WORKDIR /home/mcx/cxblog
# 复制jar文件到路径
COPY ./jar/cxblog-visual-monitor.jar /home/mcx/cxblog/cxblog-visual-monitor.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","cxblog-visual-monitor.jar"]
